"""The review workflow around the findings: wording, dashboard, report, isolation.

Phase 4 of the completion plan. The decision words are the founder's (D-055);
the report must keep CA-Guard's observation and the reviewer's decision
visibly apart; and on the public demo, one visitor must never reach another's
engagement through any route at all.
"""

from __future__ import annotations

import io
import re
import sqlite3
from pathlib import Path
from typing import cast

import pandas as pd
import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from caguard.api.app import create_app
from caguard.benchmark.generator import GeneratorConfig, generate
from caguard.review.decisions import DECISION_LABELS, ReviewAction
from caguard.review.store import SCHEMA_VERSION, ReviewStore

INVITE = "firm-invite-code"
PASS = "a-long-enough-passphrase"


@pytest.fixture(scope="module")
def csv_bytes() -> bytes:
    buffer = io.StringIO()
    generate(GeneratorConfig(seed=808, n_vouchers=400)).lines.to_csv(buffer, index=False)
    return buffer.getvalue().encode()


@pytest.fixture(autouse=True)
def _invite(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("CAGUARD_INVITE_CODE", INVITE)
    monkeypatch.delenv("CAGUARD_DEMO", raising=False)


def _client(store: Path, email: str) -> TestClient:
    client = TestClient(create_app(store))
    body = {"email": email, "name": email.split("@")[0], "password": PASS, "invite_code": INVITE}
    if client.post("/api/auth/signup", json=body).status_code != 200:
        assert client.post("/api/auth/login", json={"email": email, "password": PASS}).is_success
    return client


def _upload(client: TestClient, payload: bytes, name: str = "books.csv") -> dict:
    response = client.post("/api/engagements", files={"file": (name, payload, "text/csv")})
    assert response.status_code == 200, response.text
    return response.json()


# --- wording ---------------------------------------------------------------------------


def test_every_decision_has_a_label_and_none_says_accept_or_reject() -> None:
    assert set(DECISION_LABELS) == set(ReviewAction)
    for label in DECISION_LABELS.values():
        assert not re.search(r"\b(accept|reject)", label, re.IGNORECASE), label


# --- the report -------------------------------------------------------------------------


def test_the_report_separates_observation_from_decision_and_documents_selection(
    tmp_path: Path, csv_bytes: bytes
) -> None:
    client = _client(tmp_path / "review.db", "partner@firm.in")
    queue = _upload(client, csv_bytes)
    engagement = queue["engagement"]["id"]
    first, second, third = (f["voucher_id"] for f in queue["findings"][:3])
    client.post(
        f"/api/engagements/{engagement}/decisions", json={"voucher_id": first, "action": "accept"}
    )
    client.post(
        f"/api/engagements/{engagement}/decisions",
        json={"voucher_id": second, "action": "reject", "note": "invoice seen and agreed"},
    )
    client.post(
        f"/api/engagements/{engagement}/decisions",
        json={"voucher_id": third, "action": "investigate"},
    )

    report = client.get(f"/api/engagements/{engagement}/report.html").text

    assert "What CA-Guard observed" in report
    assert "What the reviewer decided" in report
    assert "How these items were selected" in report and "SA 530" in report
    assert "Exception — follow up" in report and "Cleared — not a concern" in report
    (source,) = client.get(f"/api/engagements/{engagement}/sources").json()
    assert source["sha256"] in report, "the report names the exact file it was built from"
    assert "Generated by" in report and "partner" in report
    assert "investigateed" not in report.lower()
    assert "audit opinion" in report  # ... in the sentence saying it does not issue one
    assert "invoice seen and agreed" in report


def test_the_csv_carries_a_readable_decision_and_a_stable_code(
    tmp_path: Path, csv_bytes: bytes
) -> None:
    client = _client(tmp_path / "review.db", "partner@firm.in")
    queue = _upload(client, csv_bytes)
    engagement = queue["engagement"]["id"]
    voucher = queue["findings"][0]["voucher_id"]
    client.post(
        f"/api/engagements/{engagement}/decisions", json={"voucher_id": voucher, "action": "accept"}
    )

    frame = pd.read_csv(io.StringIO(client.get(f"/api/engagements/{engagement}/report.csv").text))
    row = frame[frame.voucher_id == voucher].iloc[0]
    assert row.reviewer_decision == "Exception — follow up"
    assert row.status_code == "accept"
    assert row.decided_at.endswith("UTC")


# --- the dashboard ------------------------------------------------------------------------


def test_the_dashboard_shows_progress_without_reanalysing(tmp_path: Path, csv_bytes: bytes) -> None:
    store = tmp_path / "review.db"
    client = _client(store, "partner@firm.in")
    queue = _upload(client, csv_bytes)
    engagement = queue["engagement"]["id"]
    for finding in queue["findings"][:2]:
        client.post(
            f"/api/engagements/{engagement}/decisions",
            json={"voucher_id": finding["voucher_id"], "action": "investigate"},
        )

    fresh = _client(store, "partner@firm.in")  # a new process: nothing in memory
    (row,) = fresh.get("/api/engagements").json()

    assert row["flagged"] == queue["flagged"]
    assert row["high"] == queue["bands"]["high"]
    assert row["reviewed"] == 2
    assert row["latest_file"] == "books.csv"
    app = cast(FastAPI, fresh.app)
    assert not app.state.workspace.analyses, "listing must not analyse anything"


def test_an_engagement_can_be_renamed_and_the_name_carries_into_the_report(
    tmp_path: Path, csv_bytes: bytes
) -> None:
    client = _client(tmp_path / "review.db", "partner@firm.in")
    engagement = _upload(client, csv_bytes)["engagement"]["id"]

    renamed = client.patch(f"/api/engagements/{engagement}", json={"name": "Sharma Traders — FY25"})
    assert renamed.status_code == 200
    assert client.get("/api/engagements").json()[0]["engagement"]["name"] == "Sharma Traders — FY25"
    assert "Sharma Traders — FY25" in client.get(f"/api/engagements/{engagement}/report.html").text

    assert (
        client.patch(f"/api/engagements/{engagement}", json={"name": "x" * 121}).status_code == 422
    )
    restored = client.patch(f"/api/engagements/{engagement}", json={"name": "  "}).json()
    assert restored["name"] != "  " and restored["name"].strip()


# --- isolation on the public demo -----------------------------------------------------------


def test_self_hosted_reviewers_share_the_firms_engagements(
    tmp_path: Path, csv_bytes: bytes
) -> None:
    store = tmp_path / "review.db"
    partner = _client(store, "partner@firm.in")
    engagement = _upload(partner, csv_bytes)["engagement"]["id"]

    article = _client(store, "article@firm.in")
    assert article.get(f"/api/engagements/{engagement}/queue").status_code == 200
    assert len(article.get("/api/engagements").json()) == 1


def test_demo_visitors_never_reach_each_others_engagements(
    tmp_path: Path, csv_bytes: bytes, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("CAGUARD_DEMO", "1")
    store = tmp_path / "review.db"
    alice = _client(store, "alice@example.com")
    queue = _upload(alice, csv_bytes)
    engagement = queue["engagement"]["id"]
    voucher = queue["findings"][0]["voucher_id"]
    (source,) = alice.get(f"/api/engagements/{engagement}/sources").json()

    bob = _client(store, "bob@example.com")
    assert bob.get("/api/engagements").json() == []
    base = f"/api/engagements/{engagement}"
    attempts = [
        ("get", f"{base}/queue", None),
        ("get", f"{base}/findings/{voucher}", None),
        ("get", f"{base}/findings/{voucher}/explanation", None),
        ("post", f"{base}/decisions", {"voucher_id": voucher, "action": "accept"}),
        ("get", f"{base}/trail", None),
        ("get", f"{base}/report.csv", None),
        ("get", f"{base}/report.html", None),
        ("patch", base, {"name": "mine now"}),
        ("get", f"{base}/sources", None),
        ("get", f"{base}/sources/{source['id']}/original", None),
        ("get", f"{base}/sources/{source['id']}/preview", None),
        ("delete", f"{base}/sources/{source['id']}", None),
    ]
    for method, url, body in attempts:
        response = getattr(bob, method)(url, **({"json": body} if body else {}))
        assert response.status_code == 404, (method, url, response.status_code)

    # The same sample ledger uploaded by Bob is his own engagement, not Alice's.
    own = _upload(bob, csv_bytes)["engagement"]["id"]
    assert own != engagement
    assert alice.get(f"{base}/trail").json() == []
    assert len(alice.get("/api/engagements").json()) == 1


# --- the database upgrade ------------------------------------------------------------------


def test_a_version_2_database_upgrades_to_3_and_keeps_everything(
    tmp_path: Path, csv_bytes: bytes
) -> None:
    store = tmp_path / "review.db"
    client = _client(store, "partner@firm.in")
    queue = _upload(client, csv_bytes)
    engagement = queue["engagement"]["id"]
    voucher = queue["findings"][0]["voucher_id"]
    client.post(
        f"/api/engagements/{engagement}/decisions", json={"voucher_id": voucher, "action": "accept"}
    )

    # Rewind the file to version 2, as a previous build would have left it.
    with sqlite3.connect(store) as connection:
        connection.execute("DROP TABLE engagement_stats")
        connection.execute("ALTER TABLE engagements DROP COLUMN display_name")
        connection.execute("ALTER TABLE engagements DROP COLUMN owner_id")
        connection.execute("UPDATE schema_version SET version = 2")

    upgraded = ReviewStore(store)
    with sqlite3.connect(store) as connection:
        assert connection.execute("SELECT version FROM schema_version").fetchone() == (
            SCHEMA_VERSION,
        )
    assert len(upgraded.trail(engagement)) == 1
    assert upgraded.sources(engagement)
    (summary,) = upgraded.summaries()
    assert summary.flagged is None, "unknown until analysed again — not guessed"
    assert summary.reviewed == 1


def test_queue_rows_carry_what_search_needs_and_not_the_signal_working(
    tmp_path: Path, csv_bytes: bytes
) -> None:
    client = _client(tmp_path / "review.db", "partner@firm.in")
    queue = _upload(client, csv_bytes)
    first = queue["findings"][0]
    assert first["accounts"], "account names, so a reviewer can search by them"
    assert all(signal["evidence"] == {} for f in queue["findings"] for signal in f["signals"])

    single = client.get(
        f"/api/engagements/{queue['engagement']['id']}/findings/{first['voucher_id']}"
    )
    assert any(signal["evidence"] for signal in single.json()["signals"])
